[tools]
aws-cli = "latest"
fzf = "latest"
starship = "latest"
usage = "latest"
gh = "latest"
jq = "latest"

cargo-binstall = "latest"
bat = "latest"
delta = "latest"
fd = "latest"
just = "latest"
ripgrep = "latest"
zoxide = "latest"

node = "lts"
pnpm = "latest"
bun = "latest"
deno = "latest"
"npm:wrangler" = "latest"
"npm:nx" = "latest"
"npm:@typescript/native-preview" = "latest"
"npm:@google/gemini-cli" = "latest"

python = "latest"
uv = "latest"
"pipx:oci-cli" = "latest"

ruby = "latest"
"gem:cocoapods" = "latest"
"gem:fastlane" = "latest"
"vfox:mise-plugins/vfox-yarn" = "latest"
"cargo:eza" = "latest"

[settings]
experimental = true
disable_backends = ["asdf"]

[settings.npm]
package_manager = "pnpm"
